### PR TITLE
Use Mu Devops

### PR DESCRIPTION
**Pull request by makubacki**
Updates this repository to use the consolidated YAML template resources
provided at microsoft/mu_devops for its Azure DevOps pipelines.

The following remaining YAML files build against the latest templates in
mu_devops main branch by defining a repository resource in the YAML
file:
  - .azurepipelines\Ubuntu-GCC5.yml
  - .azurepipelines\Windows-VS.yml

These YAML files have been tested to support this repository's builds as
visible in the Project Mu pipelines.

https://dev.azure.com/projectmu/mu/_build

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>

### CODE REVIEW

**Comment by makubacki** [comment]
Note: The build results (with existing pipelines) do not reflect the build results with this change. Please go here to see what the results look like with this PR - [Pipelines/Mu DevOps CI Testing](https://dev.azure.com/projectmu/mu/_build?definitionScope=%5CMu%20DevOps%20CI%20Testing).

**Review by kuqin12 — APPROVED** [review]
This change looks good, but it somehow failed the pipeline checks?

**Comment by kuqin12** [comment]
> This change looks good, but it somehow failed the pipeline checks?

Also, what is

**Comment by makubacki** [comment]
> This change looks good, but it somehow failed the pipeline checks?

I mentioned in another comment that the pipelines will fail as the pre-existing pipelines are set to the microsoft repo main branch (which does not have the new YAML file changes).

The new YAML has been tested against the new pipelines set up for my fork. Once the changes are in the microsoft repo main branch the new pipelines will be pointed there to work with the new YAML files there.

**Comment by makubacki** [comment]
> Also, is there possibility to remove the py script?

Which Python script would are you talking about? CISettings.py?

**Comment by kuqin12** [comment]
> > Also, is there possibility to remove the py script?
> 
> Which Python script would are you talking about? CISettings.py?

Correct. But it seems that it contains too many repo specific information. It is probably not feasible to centralize it.

**Review by cfernald — APPROVED** [review]

**Pull request merged**
